[project]
name = "forage-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "camoufox>=0.4.11",
    "fastapi>=0.128.8",
    "httpx>=0.28.1",
    "playwright>=1.58.0",
    "uvicorn>=0.40.0",
]
